name: Release Workflow
on: [create]

permissions:
  contents: write

jobs:
  release:
    if: github.event_name == 'create' && github.event.ref_type == 'tag'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: make BUILD_STATIC=yes BUILD_SHARED=no CFLAGS="-static -O3" LDFLAGS="--static -O3"
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "programs/lz4"
          tag: ${{ github.ref }}
          name: ${{ github.ref }}
          draft: true